; Headless tests of the screen model. Like ches_screen, must not depend on bonsai or
; bonsai_term.

(copy_files# ../../test/key_notation.ml)

(library
 (name ches_screen_test)
 (libraries ches_error ches_app ches_core ches_input ches_palette ches_screen ches_highlight core expect_test_helpers_core)
 ; See core/dune for why this flag is needed.
 (inline_tests
  (flags
   (:standard -source-tree-root .)))
 (preprocess
  (pps ppx_jane)))
